[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Utils = "a6a4a4df-ba9f-45e9-bafc-bec3296762b9"
